---

- name: "cert-self-signed: Generate an OpenSSL private key (default 4096 bits, RSA)"
  openssl_privatekey:
    path: "{{ certificate_dir_private }}/{{ item.private }}"
    passphrase: "{{ item.passphrase | default(omit) }}"
    cipher: "{{ item.cipher | default(omit) }}"
  loop: "{{ certificate_self_signed }}"
  when: not ansible_check_mode

- name: "cert-self-signed: Generate an OpenSSL Certificate Signing Request"
  openssl_csr:
    path: "{{ certificate_dir_csr }}/{{ item.csr }}"
    privatekey_path: "{{ certificate_dir_private }}/{{ item.private }}"
    privatekey_passphrase: "{{ item.passphrase | default(omit) }}"
    common_name: "{{ item.CN }}"
  loop: "{{ certificate_self_signed }}"
  when: not ansible_check_mode

- name: "cert-self-signed: Generate a Self Signed OpenSSL certificate"
  openssl_certificate:
    provider: "selfsigned"
    path: "{{ certificate_dir_certs }}/{{ item.crt }}"
    csr_path: "{{ certificate_dir_csr }}/{{ item.csr }}"
    privatekey_path: "{{ certificate_dir_private }}/{{ item.private }}"
    privatekey_passphrase: "{{ item.passphrase | default(omit) }}"
  loop: "{{ certificate_self_signed }}"
  when: not ansible_check_mode

# EOF
...
